# Generated by Django 2.0.2 on 2018-02-16 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersClasses',
            fields=[
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('monday', models.PositiveSmallIntegerField(default=0, verbose_name='周一课程')),
                ('tuesday', models.PositiveSmallIntegerField(default=0, verbose_name='周二课程')),
                ('wednesday', models.PositiveSmallIntegerField(default=0, verbose_name='周三课程')),
                ('thursday', models.PositiveSmallIntegerField(default=0, verbose_name='周四课程')),
                ('friday', models.PositiveSmallIntegerField(default=0, verbose_name='周五课程')),
            ],
            options={
                'verbose_name': '社团成员课程时间',
                'verbose_name_plural': '社团成员课程时间',
                'db_table': 'members_classes',
            },
        ),
        migrations.RemoveField(
            model_name='members',
            name='is_activiting',
        ),
        migrations.AddField(
            model_name='members',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
        migrations.AddField(
            model_name='members',
            name='is_auth',
            field=models.BooleanField(default=False, verbose_name='是否认证'),
        ),
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='学号'),
        ),
    ]
