# Generated by Django 2.0.3 on 2018-03-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='date_joined',
            field=models.DateField(verbose_name='加入社团时间'),
        ),
    ]
