# Generated by Django 2.0.2 on 2018-02-16 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180216_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersclasses',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='成员'),
        ),
    ]
