# Generated by Django 2.0.2 on 2018-05-14 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('reg_start', models.DateTimeField(verbose_name='报名开始时间')),
                ('reg_end', models.DateTimeField(verbose_name='报名结束时间')),
                ('start', models.DateTimeField(verbose_name='赛事开始时间')),
                ('description', models.CharField(max_length=500, verbose_name='赛事简介')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='league/%(this.name)', verbose_name='赛事宣传照片')),
                ('category', models.CharField(choices=[('university', '学校赛事'), ('association', '足协赛事'), ('friend', '友谊赛')], max_length=11, verbose_name='赛事类别')),
                ('status', models.SmallIntegerField(default=-1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '赛事',
                'verbose_name_plural': '赛事',
                'db_table': 'league',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='LeagueTeamMemberSignup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('status', models.BooleanField(default=False, verbose_name='报名审核结果')),
            ],
            options={
                'verbose_name': '赛事队员报名',
                'verbose_name_plural': '赛事队员报名',
                'db_table': 'league_team_member_signup',
            },
        ),
        migrations.CreateModel(
            name='LeagueTeamSignup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('status', models.SmallIntegerField(default=-1, verbose_name='状态')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League', verbose_name='赛事')),
            ],
            options={
                'verbose_name': '赛事队伍报名',
                'verbose_name_plural': '赛事队伍报名',
                'db_table': 'league_team_signup',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('place', models.CharField(max_length=10, verbose_name='地点')),
                ('result', models.CharField(default='-:-', max_length=5, verbose_name='结果')),
                ('category', models.CharField(choices=[('normal', '普通'), ('group', '小组赛'), ('knockout', '淘汰赛')], max_length=5)),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('category', models.CharField(choices=[('debut', '首发'), ('sub', '换人'), ('goal', '进球'), ('assist', '助攻'), ('foul', '犯规'), ('yellow', '黄牌'), ('red', '红牌')], max_length=7, verbose_name='类别')),
                ('time', models.CharField(max_length=3, verbose_name='时间')),
                ('remind', models.CharField(max_length=20, verbose_name='备注')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Match', verbose_name='比赛')),
                ('sub', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_teammate', to='league.LeagueTeamMemberSignup', verbose_name='替换队员')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teammate', to='league.LeagueTeamMemberSignup', verbose_name='队员')),
            ],
            options={
                'verbose_name': '比赛数据',
                'verbose_name_plural': '比赛数据',
                'db_table': 'match_data',
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(default=0, verbose_name='裁判等级')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '裁判',
                'verbose_name_plural': '裁判',
                'db_table': 'referee',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=10, verbose_name='队名')),
                ('logo', models.ImageField(default='team/sufa/sufa.png', upload_to='team/%(this.name)/logo', verbose_name='队徽')),
                ('description', models.CharField(max_length=200, verbose_name='队伍简介')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '队伍',
                'verbose_name_plural': '队伍',
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('num', models.CharField(max_length=2, null=True, verbose_name='号码')),
                ('join', models.DateField(null=True, verbose_name='入队时间')),
                ('leave', models.DateField(null=True, verbose_name='离队时间')),
                ('status', models.SmallIntegerField(default=-1, verbose_name='状态')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Team', verbose_name='队伍')),
            ],
            options={
                'verbose_name': '队伍成员',
                'verbose_name_plural': '队伍成员',
                'db_table': 'team_member',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='league.Team', verbose_name='客队'),
        ),
        migrations.AddField(
            model_name='match',
            name='fourth_referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forth', to='league.Referee', verbose_name='第四助理裁判'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='league.Team', verbose_name='主队'),
        ),
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League', verbose_name='赛事'),
        ),
        migrations.AddField(
            model_name='match',
            name='master_referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master', to='league.Referee', verbose_name='主裁'),
        ),
        migrations.AddField(
            model_name='match',
            name='second_referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='league.Referee', verbose_name='第二助理裁判'),
        ),
        migrations.AddField(
            model_name='match',
            name='third_referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third', to='league.Referee', verbose_name='第三助理裁判'),
        ),
        migrations.AddField(
            model_name='leagueteamsignup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Team', verbose_name='队伍'),
        ),
        migrations.AddField(
            model_name='leagueteammembersignup',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.TeamMember', verbose_name='队伍成员'),
        ),
        migrations.AddField(
            model_name='leagueteammembersignup',
            name='team_signup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.LeagueTeamSignup', verbose_name='赛事队伍报名'),
        ),
        migrations.AlterUniqueTogether(
            name='leagueteamsignup',
            unique_together={('league', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='leagueteammembersignup',
            unique_together={('team_signup', 'team_member')},
        ),
    ]
