# Generated by Django 2.0.2 on 2018-05-14 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=5, verbose_name='性别')),
                ('mobile', models.CharField(max_length=11, unique=True, verbose_name='电话')),
                ('campus', models.CharField(choices=[('BS', '宝山'), ('YC', '延长'), ('JD', '嘉定')], default='BS', max_length=2, verbose_name='校区')),
                ('favorite_club', models.CharField(max_length=20, verbose_name='喜爱的球队')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member/', verbose_name='证件照')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='加入社团时间')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否是社团骨干')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('is_auth', models.BooleanField(default=False, verbose_name='是否认证')),
            ],
            options={
                'verbose_name': '社团成员信息',
                'verbose_name_plural': '社团成员信息',
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('description', models.CharField(max_length=200, verbose_name='简介')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('description', models.CharField(max_length=50, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='PermissionToDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Department', verbose_name='部门')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '部门权限',
                'verbose_name_plural': '部门权限',
                'db_table': 'permission_to_department',
            },
        ),
        migrations.CreateModel(
            name='PermissionToPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '职位权限',
                'verbose_name_plural': '职位权限',
                'db_table': 'permission_to_position',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=10, verbose_name='名称')),
                ('remind', models.CharField(blank=True, max_length=200, verbose_name='提醒事项')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Department', verbose_name='所属部门')),
                ('permission', models.ManyToManyField(through='member.PermissionToPosition', to='member.Permission', verbose_name='职位权限')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('introduction', models.CharField(max_length=200, verbose_name='自我介绍')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Position', verbose_name='职位')),
            ],
            options={
                'verbose_name': '社团骨干',
                'verbose_name_plural': '社团骨干',
                'db_table': 'administrator',
            },
        ),
        migrations.CreateModel(
            name='MemberClasses',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('monday', models.PositiveSmallIntegerField(default=0, verbose_name='周一课程')),
                ('tuesday', models.PositiveSmallIntegerField(default=0, verbose_name='周二课程')),
                ('wednesday', models.PositiveSmallIntegerField(default=0, verbose_name='周三课程')),
                ('thursday', models.PositiveSmallIntegerField(default=0, verbose_name='周四课程')),
                ('friday', models.PositiveSmallIntegerField(default=0, verbose_name='周五课程')),
            ],
            options={
                'verbose_name': '社团成员课程时间',
                'verbose_name_plural': '社团成员课程时间',
                'db_table': 'members_classes',
            },
        ),
        migrations.AddField(
            model_name='permissiontoposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Position', verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='department',
            name='permission',
            field=models.ManyToManyField(through='member.PermissionToDepartment', to='member.Permission', verbose_name='部门权限'),
        ),
        migrations.AlterUniqueTogether(
            name='permissiontoposition',
            unique_together={('permission', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='permissiontodepartment',
            unique_together={('permission', 'department')},
        ),
    ]
