# Generated by Django 2.0.4 on 2018-04-24 08:18

from django.db import migrations


def departments(apps, schema_editor):
    Department = apps.get_model("member", "Department")
    db_alias = schema_editor.connection.alias
    Department.objects.using(db_alias).bulk_create([
        Department(name='指导老师', description='社团指导老师'),
        Department(name='主席团', description='管理社团工作，组织社团赛事，安排社团活动'),
        Department(name='事务部', description='社团日常事务处理，比赛、活动规划及事务安排'),
        Department(name='外联部', description='联系比赛参与队伍及队员，通知比赛、活动信息，拉赞助'),
        Department(name='宣传部', description='社团宣传，比赛、活动宣传'),
        Department(name='财务部', description='管理记录社团经费收入开销'),
        Department(name='技术部', description='开放维护社团管理平台'),
        Department(name='裁判协会', description='裁判培训，安排比赛裁判'),
        Department(name='校队', description='校队事务管理'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(departments),
    ]
