# Generated by Django 2.0.4 on 2018-05-22 07:37

from django.db import migrations


def permissions(apps, schema_editor):
    Permission = apps.get_model("member", "Permission")
    db_alias = schema_editor.connection.alias
    Permission.objects.using(db_alias).bulk_create([
        Permission(name='任命指导老师', description='任命指导老师'),
        Permission(name='任命社长', description='任命下一任社长'),
        Permission(name='任命副社长', description='任命副社长'),
        Permission(name='任命部长', description='任命各部门下一任部长'),
        Permission(name='任命事务部副部长', description='任命事务部副部长'),
        Permission(name='任命外联部副部长', description='任命外联部副部长'),
        Permission(name='任命宣传部副部长', description='任命宣传部副部长'),
        Permission(name='任命财务部副部长', description='任命财务部副部长'),
        Permission(name='任命技术部副部长', description='任命技术部副部长'),
        Permission(name='任命裁判协会副会长', description='任命裁判协会副会长'),
        Permission(name='任命男足队长', description='任命男足下一任队长'),
        Permission(name='任命女足队长', description='任命女足下一任队长'),
        Permission(name='任命男足经理', description='任命男足下一任经理'),
        Permission(name='任命女足经理', description='任命女足下一任经理'),
        Permission(name='更改权限', description='更改部门、职位拥有权限'),
        Permission(name='社团部门、职位管理', description='增设或移除社团部门、职位'),
        Permission(name='批准社团骨干申请及所属部门管理', description='审核社团成员申请信息，批准申请'),
        Permission(name='批准男足队员入队', description='根据队伍选拔的结果，批准入队'),
        Permission(name='批准女足队员入队', description='根据队伍选拔的结果，批准入队'),
        Permission(name='批准队伍申报', description='审核队伍信息，批准申请'),
        Permission(name='批准赛事', description='审核赛事，批准申报'),
        Permission(name='批准队伍报名', description='审核队伍参赛名单，批准报名'),
        Permission(name='批准活动', description='审核活动内容及举办方式，批准申报'),
        Permission(name='批准新闻发布', description='审核新闻内容，批准发布'),
        Permission(name='安排分组及赛程', description='安排赛事分组及赛程'),
        Permission(name='安排比赛裁判', description='安排比赛负责裁判'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20180522_0737'),
    ]

    operations = [
        migrations.RunPython(permissions),
    ]
