# Generated by Django 2.0.4 on 2018-05-22 08:17

from django.db import migrations


def permissions_to_department(apps, schema_editor):
    PermissionToDepartment = apps.get_model("member", "PermissionToDepartment")
    db_alias = schema_editor.connection.alias
    PermissionToDepartment.objects.using(db_alias).bulk_create([
        PermissionToDepartment(permission_id=1, department_id=1),
        PermissionToDepartment(permission_id=2, department_id=1),
        PermissionToDepartment(permission_id=3, department_id=1),
        PermissionToDepartment(permission_id=4, department_id=1),
        PermissionToDepartment(permission_id=5, department_id=1),
        PermissionToDepartment(permission_id=6, department_id=1),
        PermissionToDepartment(permission_id=7, department_id=1),
        PermissionToDepartment(permission_id=8, department_id=1),
        PermissionToDepartment(permission_id=9, department_id=1),
        PermissionToDepartment(permission_id=10, department_id=1),
        PermissionToDepartment(permission_id=11, department_id=1),
        PermissionToDepartment(permission_id=12, department_id=1),
        PermissionToDepartment(permission_id=13, department_id=1),
        PermissionToDepartment(permission_id=14, department_id=1),
        PermissionToDepartment(permission_id=15, department_id=1),
        PermissionToDepartment(permission_id=16, department_id=1),
        PermissionToDepartment(permission_id=17, department_id=1),
        PermissionToDepartment(permission_id=18, department_id=1),
        PermissionToDepartment(permission_id=19, department_id=1),
        PermissionToDepartment(permission_id=20, department_id=1),
        PermissionToDepartment(permission_id=21, department_id=1),
        PermissionToDepartment(permission_id=22, department_id=1),
        PermissionToDepartment(permission_id=23, department_id=1),
        PermissionToDepartment(permission_id=24, department_id=1),
        PermissionToDepartment(permission_id=25, department_id=1),
        PermissionToDepartment(permission_id=26, department_id=1),
        PermissionToDepartment(permission_id=5, department_id=2),
        PermissionToDepartment(permission_id=6, department_id=2),
        PermissionToDepartment(permission_id=7, department_id=2),
        PermissionToDepartment(permission_id=8, department_id=2),
        PermissionToDepartment(permission_id=9, department_id=2),
        PermissionToDepartment(permission_id=10, department_id=2),
        PermissionToDepartment(permission_id=13, department_id=2),
        PermissionToDepartment(permission_id=14, department_id=2),
        PermissionToDepartment(permission_id=15, department_id=2),
        PermissionToDepartment(permission_id=16, department_id=2),
        PermissionToDepartment(permission_id=17, department_id=2),
        PermissionToDepartment(permission_id=18, department_id=2),
        PermissionToDepartment(permission_id=19, department_id=2),
        PermissionToDepartment(permission_id=20, department_id=2),
        PermissionToDepartment(permission_id=21, department_id=2),
        PermissionToDepartment(permission_id=22, department_id=2),
        PermissionToDepartment(permission_id=23, department_id=2),
        PermissionToDepartment(permission_id=24, department_id=2),
        PermissionToDepartment(permission_id=25, department_id=2),
        PermissionToDepartment(permission_id=26, department_id=2),
        PermissionToDepartment(permission_id=20, department_id=3),
        PermissionToDepartment(permission_id=22, department_id=3),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20180522_0737'),
    ]

    operations = [
        migrations.RunPython(permissions_to_department),
    ]
