# Generated by Django 2.0.4 on 2018-05-22 08:17

from django.db import migrations


def permissions_to_position(apps, schema_editor):
    PermissionToPosition = apps.get_model("member", "PermissionToDepartment")
    db_alias = schema_editor.connection.alias
    PermissionToPosition.objects.using(db_alias).bulk_create([
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20180522_0817'),
    ]

    operations = [
        migrations.RunPython(permissions_to_position),
    ]
