# Generated by Django 2.0.4 on 2018-04-24 08:18

from django.db import migrations


def departments(apps, schema_editor):
    Departments = apps.get_model("admins", "Departments")
    db_alias = schema_editor.connection.alias
    Departments.objects.using(db_alias).bulk_create([
        Departments(name='指导老师', description='社团指导老师'),
        Departments(name='主席团', description='管理社团工作，组织社团赛事，安排社团活动'),
        Departments(name='事务部', description='社团日常事务处理，比赛、活动规划及事务安排'),
        Departments(name='外联部', description='联系比赛参与队伍及队员，通知比赛、活动信息，拉赞助'),
        Departments(name='宣传部', description='社团宣传，比赛、活动宣传'),
        Departments(name='财务部', description='管理记录社团经费收入开销'),
        Departments(name='技术部', description='开放维护社团管理平台'),
        Departments(name='裁判协会', description='裁判培训，安排比赛裁判'),
        Departments(name='校队经理', description='校队事务管理，校队宣传'),
    ])

# TODO: 职位、权限设置


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(departments),
    ]
