# Generated by Django 2.0.4 on 2018-04-10 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('reg_start', models.DateTimeField(verbose_name='报名开始时间')),
                ('reg_end', models.DateTimeField(verbose_name='报名结束时间')),
                ('start', models.DateTimeField(verbose_name='赛事开始时间')),
                ('description', models.CharField(max_length=500, verbose_name='赛事简介')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leagues/%(this.name)', verbose_name='赛事宣传照片')),
                ('category', models.CharField(choices=[('university', '学校赛事'), ('association', '足协赛事'), ('friend', '友谊赛')], max_length=11, verbose_name='赛事类别')),
                ('status', models.SmallIntegerField(default=-1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '赛事',
                'verbose_name_plural': '赛事',
                'db_table': 'leagues',
            },
        ),
        migrations.CreateModel(
            name='LeaguesSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=-1, verbose_name='状态')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Leagues', verbose_name='赛事')),
            ],
            options={
                'verbose_name': '赛事报名',
                'verbose_name_plural': '赛事报名',
                'db_table': 'leagues_signup',
            },
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('place', models.CharField(max_length=10, verbose_name='地点')),
                ('result', models.CharField(default='-:-', max_length=5, verbose_name='结果')),
                ('category', models.CharField(choices=[('normal', '普通'), ('group', '小组赛'), ('knockout', '淘汰赛')], max_length=5)),
            ],
            options={
                'verbose_name': '比赛',
                'verbose_name_plural': '比赛',
                'db_table': 'matches',
            },
        ),
        migrations.CreateModel(
            name='MatchesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('category', models.CharField(choices=[('debut', '首发'), ('sub', '换人'), ('goal', '进球'), ('assist', '助攻'), ('foul', '犯规'), ('yellow', '黄牌'), ('red', '红牌')], max_length=7, verbose_name='类别')),
                ('time', models.CharField(max_length=3, verbose_name='时间')),
                ('remind', models.CharField(max_length=20, verbose_name='备注')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Matches', verbose_name='比赛')),
            ],
            options={
                'verbose_name': '比赛数据',
                'verbose_name_plural': '比赛数据',
                'db_table': 'matches_data',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='编号')),
                ('name', models.CharField(max_length=10, verbose_name='队名')),
                ('logo', models.ImageField(default='team/sufa/sufa.png', upload_to='team/%(this.name)/logo', verbose_name='队徽')),
                ('description', models.CharField(max_length=200, verbose_name='队伍简介')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.BooleanField(default=False, verbose_name='状态')),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '队伍',
                'verbose_name_plural': '队伍',
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='TeamsMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('num', models.CharField(max_length=2, null=True, verbose_name='号码')),
                ('join', models.DateField(null=True, verbose_name='入队时间')),
                ('leave', models.DateField(null=True, verbose_name='离队时间')),
                ('status', models.SmallIntegerField(default=-1, verbose_name='状态')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Teams', verbose_name='队伍')),
            ],
            options={
                'verbose_name': '队伍成员',
                'verbose_name_plural': '队伍成员',
                'db_table': 'teams_members',
            },
        ),
        migrations.AddField(
            model_name='matchesdata',
            name='sub',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub', to='leagues.TeamsMembers', verbose_name='替换队员'),
        ),
        migrations.AddField(
            model_name='matchesdata',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teammate', to='leagues.TeamsMembers', verbose_name='队员'),
        ),
        migrations.AddField(
            model_name='matches',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='leagues.Teams', verbose_name='客队'),
        ),
        migrations.AddField(
            model_name='matches',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='leagues.Teams', verbose_name='主队'),
        ),
        migrations.AddField(
            model_name='matches',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Leagues', verbose_name='赛事'),
        ),
        migrations.AddField(
            model_name='leaguessignup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.Teams', verbose_name='队伍'),
        ),
        migrations.AlterUniqueTogether(
            name='leaguessignup',
            unique_together={('league', 'team')},
        ),
    ]
