# Generated by Django 2.0.4 on 2018-04-09 23:13

from django.db import migrations


def college_teams(apps, schema_editor):
    Team = apps.get_model("leagues", "Teams")
    db_alias = schema_editor.connection.alias
    Team.objects.using(db_alias).bulk_create([
        Team(id=1, name='国际交流学院',        logo='team/sufa/sufa.png', description=''),
        Team(id=2, name='社区学院理工一组',     logo='team/sufa/sufa.png', description=''),
        Team(id=3, name='社区学院理工二组',     logo='team/sufa/sufa.png', description=''),
        Team(id=4, name='社区学院理工三组',     logo='team/sufa/sufa.png', description=''),
        Team(id=5, name='社区学院人文经管',     logo='team/sufa/sufa.png', description=''),
        Team(id=6, name='理学院',             logo='team/sufa/sufa.png', description=''),
        Team(id=7, name='生命科学学院',        logo='team/sufa/sufa.png', description=''),
        Team(id=8, name='文学院',             logo='team/sufa/sufa.png', description=''),
        Team(id=9, name='法学院',             logo='team/sufa/sufa.png', description=''),
        Team(id=10, name='外国语学院',         logo='team/sufa/sufa.png', description=''),
        Team(id=11, name='社会学院',           logo='team/sufa/sufa.png', description=''),
        Team(id=12, name='社会科学学部',        logo='team/sufa/sufa.png', description=''),
        Team(id=13, name='计算机工程与科学学院', logo='team/sufa/sufa.png', description=''),
        Team(id=14, name='机电工程与自动化学院', logo='team/sufa/sufa.png', description=''),
        Team(id=15, name='通信与信息工程学院',   logo='team/sufa/sufa.png', description=''),
        Team(id=16, name='环境与化学工程学院',   logo='team/sufa/sufa.png', description=''),
        Team(id=17, name='材料科学与工程学院',   logo='team/sufa/sufa.png', description=''),
        Team(id=18, name='中欧工程技术学院',     logo='team/sufa/sufa.png', description=''),
        Team(id=19, name='土木工程系',          logo='team/sufa/sufa.png', description=''),
        Team(id=20, name='材料基因组工程研究院',  logo='team/sufa/sufa.png', description=''),
        Team(id=21, name='经济学院',            logo='team/sufa/sufa.png', description=''),
        Team(id=22, name='管理学院',            logo='team/sufa/sufa.png', description=''),
        Team(id=23, name='图书情报档案系',       logo='team/sufa/sufa.png', description=''),
        Team(id=24, name='悉尼工商学院',         logo='team/sufa/sufa.png', description=''),
        Team(id=25, name='管理教育研究院',       logo='team/sufa/sufa.png', description=''),
        Team(id=26, name='上海电影学院',         logo='team/sufa/sufa.png', description=''),
        Team(id=27, name='上海美术学院',         logo='team/sufa/sufa.png', description=''),
        Team(id=28, name='音乐学院',            logo='team/sufa/sufa.png', description=''),
        Team(id=29, name='数码艺术学院',         logo='team/sufa/sufa.png', description=''),
        Team(id=30, name='上海温哥华电影学院',    logo='team/sufa/sufa.png', description=''),
        Team(id=31, name='钱伟长学院',           logo='team/sufa/sufa.png', description=''),
        Team(id=32, name='体育学院',             logo='team/sufa/sufa.png', description=''),
        Team(id=33, name='人才学院',             logo='team/sufa/sufa.png', description=''),
        Team(id=34, name='继续教育学院',          logo='team/sufa/sufa.png', description=''),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(college_teams),
    ]
