# Generated by Django 2.0.4 on 2018-04-23 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0002_auto_20180410_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(default=0, verbose_name='裁判等级')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
            ],
            options={
                'verbose_name': '裁判',
                'verbose_name_plural': '裁判',
                'db_table': 'referee',
            },
        ),
        migrations.AddField(
            model_name='matches',
            name='fourth_referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forth', to='leagues.Referee', verbose_name='第四助理裁判'),
        ),
        migrations.AddField(
            model_name='matches',
            name='master_referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master', to='leagues.Referee', verbose_name='主裁'),
        ),
        migrations.AddField(
            model_name='matches',
            name='second_referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second', to='leagues.Referee', verbose_name='第二助理裁判'),
        ),
        migrations.AddField(
            model_name='matches',
            name='third_referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third', to='leagues.Referee', verbose_name='第三助理裁判'),
        ),
    ]
