# Generated by Django 2.0.4 on 2018-04-24 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManTeamMatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('category', models.CharField(choices=[('debut', '首发'), ('sub', '换人'), ('goal', '进球'), ('assist', '助攻'), ('yellow', '黄牌'), ('red', '红牌'), ('save', '扑救')], max_length=6, verbose_name='类别')),
                ('time', models.CharField(max_length=3, verbose_name='时间')),
                ('remind', models.CharField(max_length=20, verbose_name='备注')),
            ],
            options={
                'verbose_name': '上海大学男子足球队比赛数据',
                'verbose_name_plural': '上海大学男子足球队比赛数据',
                'db_table': 'man_team_match_data',
            },
        ),
        migrations.CreateModel(
            name='ManTeamMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('league', models.CharField(max_length=20, verbose_name='赛事')),
                ('against', models.CharField(max_length=20, verbose_name='对手')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('place', models.CharField(max_length=50, verbose_name='地点')),
                ('result', models.CharField(default='-:-', max_length=5, verbose_name='赛果')),
            ],
            options={
                'verbose_name': '上海大学男子足球队比赛',
                'verbose_name_plural': '上海大学男子足球队比赛',
                'db_table': 'man_team_matches',
            },
        ),
        migrations.CreateModel(
            name='ManTeamMembers',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('num', models.CharField(max_length=2, verbose_name='号码')),
                ('position', models.CharField(choices=[('GK', '门将'), ('CB', '中后卫'), ('RB', '右后卫'), ('LB', '左后卫'), ('DMF', '后腰'), ('CMF', '中前卫'), ('AMF', '前腰'), ('RMF', '右前卫'), ('LMF', '左前卫'), ('RS', '右前锋'), ('LS', '左前锋'), ('SS', '影锋'), ('CF', '前锋'), ('ST', '中锋')], max_length=3, verbose_name='场上位置')),
                ('height', models.CharField(default='170', max_length=3, verbose_name='身高(cm)')),
                ('weight', models.CharField(default='60', max_length=2, verbose_name='体重(kg)')),
                ('shoe_size', models.CharField(default='42', max_length=4, verbose_name='鞋码(EUR)')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '上海大学男子足球队队员',
                'verbose_name_plural': '上海大学男子足球队队员',
                'db_table': 'man_team_members',
            },
        ),
        migrations.CreateModel(
            name='WomanTeamMatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('category', models.CharField(choices=[('debut', '首发'), ('sub', '换人'), ('goal', '进球'), ('assist', '助攻'), ('yellow', '黄牌'), ('red', '红牌'), ('save', '扑救')], max_length=6, verbose_name='类别')),
                ('time', models.CharField(max_length=3, verbose_name='时间')),
                ('remind', models.CharField(max_length=20, verbose_name='备注')),
            ],
            options={
                'verbose_name': '上海大学女子足球队比赛数据',
                'verbose_name_plural': '上海大学女子足球队比赛数据',
                'db_table': 'woman_team_match_data',
            },
        ),
        migrations.CreateModel(
            name='WomanTeamMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='编号')),
                ('league', models.CharField(max_length=20, verbose_name='赛事')),
                ('against', models.CharField(max_length=20, verbose_name='对手')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('place', models.CharField(max_length=50, verbose_name='地点')),
                ('result', models.CharField(default='-:-', max_length=5, verbose_name='赛果')),
            ],
            options={
                'verbose_name': '上海大学女子足球队比赛',
                'verbose_name_plural': '上海大学女子足球队比赛',
                'db_table': 'woman_team_matches',
            },
        ),
        migrations.CreateModel(
            name='WomanTeamMembers',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('num', models.CharField(max_length=2, verbose_name='号码')),
                ('position', models.CharField(choices=[('GK', '门将'), ('CB', '中后卫'), ('RB', '右后卫'), ('LB', '左后卫'), ('DMF', '后腰'), ('CMF', '中前卫'), ('AMF', '前腰'), ('RMF', '右前卫'), ('LMF', '左前卫'), ('RS', '右前锋'), ('LS', '左前锋'), ('SS', '影锋'), ('CF', '前锋'), ('ST', '中锋')], max_length=3, verbose_name='场上位置')),
                ('height', models.CharField(default='165', max_length=3, verbose_name='身高(cm)')),
                ('weight', models.CharField(default='45', max_length=2, verbose_name='体重(kg)')),
                ('shoe_size', models.CharField(default='35', max_length=4, verbose_name='鞋码(EUR)')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
            ],
            options={
                'verbose_name': '上海大学女子足球队队员',
                'verbose_name_plural': '上海大学女子足球队队员',
                'db_table': 'woman_team_members',
            },
        ),
        migrations.AddField(
            model_name='womanteammatchdata',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.WomanTeamMatches', verbose_name='比赛'),
        ),
        migrations.AddField(
            model_name='womanteammatchdata',
            name='sub',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub', to='teams.WomanTeamMembers', verbose_name='替换队员'),
        ),
        migrations.AddField(
            model_name='womanteammatchdata',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teammate', to='teams.WomanTeamMembers', verbose_name='队员'),
        ),
        migrations.AddField(
            model_name='manteammatchdata',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.ManTeamMatches', verbose_name='比赛'),
        ),
        migrations.AddField(
            model_name='manteammatchdata',
            name='sub',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub', to='teams.ManTeamMembers', verbose_name='替换队员'),
        ),
        migrations.AddField(
            model_name='manteammatchdata',
            name='team_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teammate', to='teams.ManTeamMembers', verbose_name='队员'),
        ),
    ]
